import * as XLSX from "xlsx";

// ─── Public types ────────────────────────────────────────────────────────────

export interface CapTableSummaryRow {
  className: string;
  classCode: string; // e.g. "CS", "PA", "PA1", "PB"
  category: "common" | "preferred" | "warrant" | "convertible" | "option_pool";
  sharesAuthorized: number;
  sharesOutstanding: number;
  fullyDilutedShares: number;
  fullyDilutedOwnership: number; // decimal, e.g. 0.348
  cashRaised: number;
}

export interface CapTableStakeholder {
  id: string;
  name: string;
  holdings: Record<string, number>; // classCode → shares
  totalFullyDiluted: number;
  ownershipPercent: number;
}

export interface CapTableSummary {
  companyName: string;
  asOfDate: string; // ISO date string "YYYY-MM-DD"
  generatedBy: string;
  totalFullyDilutedShares: number;
  totalCashRaised: number;
  classes: CapTableSummaryRow[];
  stakeholders: CapTableStakeholder[];
  optionPool: {
    planName: string;
    authorized: number;
    outstanding: number;
    available: number;
  };
  safes: {
    totalAmount: number;
  };
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function toNum(v: unknown): number {
  if (v === null || v === undefined || v === "") return 0;
  if (typeof v === "number") return isNaN(v) ? 0 : v;
  const n = parseFloat(String(v).replace(/,/g, ""));
  return isNaN(n) ? 0 : n;
}

function toStr(v: unknown): string {
  if (v === null || v === undefined) return "";
  return String(v).trim();
}

/** Extract the class code from a parenthetical, e.g. "Series A Preferred (PA) Stock" → "PA" */
function extractClassCode(name: string): string {
  const m = name.match(/\(([^)]+)\)/);
  return m ? m[1].replace(/\s+/g, "") : name.replace(/\s+/g, "").toUpperCase().substring(0, 4);
}

/** Parse "As of M/D/YYYY" or "as of M/D/YYYY" from a string */
function parseAsOfDate(raw: string): string {
  const m = raw.match(/as of\s+(\d{1,2})\/(\d{1,2})\/(\d{4})/i);
  if (!m) return "";
  const [, month, day, year] = m;
  return `${year}-${month.padStart(2, "0")}-${day.padStart(2, "0")}`;
}

/**
 * Reads the raw 2D array from a given sheet name. Returns [] if not found.
 * Uses header:1 so we get string[][] (well, unknown[][]).
 */
function readSheet(workbook: XLSX.WorkBook, sheetName: string): unknown[][] {
  const sheet = workbook.Sheets[sheetName];
  if (!sheet) return [];
  return XLSX.utils.sheet_to_json(sheet, {
    header: 1,
    defval: "",
    blankrows: true,
  }) as unknown[][];
}

/**
 * Find a sheet whose name contains the given substring (case-insensitive).
 */
function findSheet(workbook: XLSX.WorkBook, substring: string): string | null {
  return (
    workbook.SheetNames.find((n) =>
      n.toLowerCase().includes(substring.toLowerCase())
    ) ?? null
  );
}

// ─── Summary sheet parser ─────────────────────────────────────────────────────

type SectionCategory =
  | "common"
  | "preferred"
  | "warrant"
  | "convertible"
  | "option_pool"
  | null;

function parseSummarySheet(rows: unknown[][]): {
  companyName: string;
  asOfDate: string;
  generatedBy: string;
  classes: CapTableSummaryRow[];
  totalFullyDilutedShares: number;
  totalCashRaised: number;
  optionPool: { planName: string; authorized: number; outstanding: number; available: number };
  safes: { totalAmount: number };
} {
  // Row 2 (index 1), col B (index 1): "Intelliga Corporation Summary Cap Table"
  const row2 = rows[1] ?? [];
  const titleCell = toStr(row2[1]);
  const companyName = titleCell.replace(/\s*Summary Cap Table\s*/i, "").trim();

  // Row 3 (index 2), col B (index 1): date/generator info
  const row3 = rows[2] ?? [];
  const metaCell = toStr(row3[1]);
  const asOfDate = parseAsOfDate(metaCell);

  // Extract "Generated by X" if present
  const genMatch = metaCell.match(/Generated by\s+(.+?)(?:\s*\||\s*$)/i);
  const generatedBy = genMatch ? genMatch[1].trim() : "Carta";

  const classes: CapTableSummaryRow[] = [];
  let currentCategory: SectionCategory = null;
  let totalFullyDilutedShares = 0;
  let totalCashRaised = 0;

  const optionPool = { planName: "", authorized: 0, outstanding: 0, available: 0 };
  const safes = { totalAmount: 0 };

  // Section header patterns
  const SECTION_PATTERNS: [RegExp, SectionCategory][] = [
    [/common stock classes/i, "common"],
    [/preferred stock classes/i, "preferred"],
    [/common stock warrants/i, "warrant"],
    [/convertibles?/i, "convertible"],
    [/equity incentive plan/i, "option_pool"],
  ];

  // Skip-row patterns (section headers, total rows, column headers)
  const SKIP_PATTERNS = [
    /^share class$/i,
    /^total common/i,
    /^total preferred/i,
    /^total warrant/i,
    /^total convertible/i,
    /^total$/i,
    /^totals$/i,
  ];

  // Track if we've already captured the "Totals" row
  let capturedTotals = false;

  // Data rows start at index 4 (row 5 in 1-based Excel)
  for (let i = 4; i < rows.length; i++) {
    const row = rows[i] ?? [];
    // Col B is index 1 in this sheet (col A is indent/empty in Carta exports)
    const colB = toStr(row[1]);

    if (!colB) continue;

    // Detect section header changes
    let isSectionHeader = false;
    for (const [pattern, category] of SECTION_PATTERNS) {
      if (pattern.test(colB)) {
        currentCategory = category;
        isSectionHeader = true;
        break;
      }
    }
    if (isSectionHeader) continue;

    // Capture Totals row
    if (/^totals?$/i.test(colB) && !capturedTotals) {
      totalFullyDilutedShares = toNum(row[4]);
      totalCashRaised = toNum(row[6]);
      capturedTotals = true;
      continue;
    }

    // Skip other total/header rows
    if (SKIP_PATTERNS.some((p) => p.test(colB))) continue;

    if (currentCategory === null) continue;

    const sharesAuthorized = toNum(row[2]);
    const sharesOutstanding = toNum(row[3]);
    const fullyDilutedShares = toNum(row[4]);
    const fullyDilutedOwnership = toNum(row[5]);
    const cashRaised = toNum(row[6]);

    // Handle option pool rows specially (RSAs, Options/RSUs, Available)
    if (currentCategory === "option_pool") {
      // The plan name row has no numeric values — it IS the plan name
      if (!optionPool.planName && sharesAuthorized === 0 && sharesOutstanding === 0) {
        optionPool.planName = colB;
        continue;
      }
      // "Available" row
      if (/available/i.test(colB)) {
        optionPool.available = sharesAuthorized || fullyDilutedShares || sharesOutstanding;
        continue;
      }
      // Outstanding options/RSUs/RSAs
      if (/option|rsu|rsa/i.test(colB)) {
        optionPool.outstanding += fullyDilutedShares || sharesOutstanding;
        optionPool.authorized += sharesAuthorized;
      }
      continue;
    }

    // Handle convertibles/SAFEs
    if (currentCategory === "convertible") {
      safes.totalAmount += cashRaised;
      // Still add to classes for display
    }

    const classCode = extractClassCode(colB);

    classes.push({
      className: colB,
      classCode,
      category: currentCategory,
      sharesAuthorized,
      sharesOutstanding,
      fullyDilutedShares,
      fullyDilutedOwnership,
      cashRaised,
    });
  }

  // Fallback: sum up if Totals row wasn't found
  if (totalFullyDilutedShares === 0) {
    totalFullyDilutedShares = classes.reduce(
      (s, c) => s + c.fullyDilutedShares,
      0
    );
  }
  if (totalCashRaised === 0) {
    totalCashRaised = classes.reduce((s, c) => s + c.cashRaised, 0);
  }

  // Set option pool totals
  if (optionPool.authorized === 0 && classes.length > 0) {
    // May not have been parsed — that's fine
  }

  return {
    companyName,
    asOfDate,
    generatedBy,
    classes,
    totalFullyDilutedShares,
    totalCashRaised,
    optionPool,
    safes,
  };
}

// ─── Intermediate sheet parser ────────────────────────────────────────────────

function parseIntermediateSheet(
  rows: unknown[][],
  classes: CapTableSummaryRow[]
): CapTableStakeholder[] {
  if (rows.length < 5) return [];

  // Row 5 (index 4) is the header row mapping columns to share class names
  const headerRow = rows[4] ?? [];

  // Build a map: column index → classCode
  // We skip col 0 (ID) and col 1 (Name). Remaining cols are share counts.
  // Carta alternates: shares, conversion ratio, shares, conversion ratio...
  // We want to skip conversion columns (they're typically fractions < 1 or labeled "1:1 Conversion")
  const colToClass: Record<number, string> = {};

  for (let colIdx = 2; colIdx < headerRow.length; colIdx++) {
    const header = toStr(headerRow[colIdx]);
    if (!header) continue;
    // Skip conversion columns
    if (/conversion|ratio|convert/i.test(header)) continue;

    // Try to match against known classes
    const code = extractClassCode(header);
    colToClass[colIdx] = code;
  }

  const stakeholders: CapTableStakeholder[] = [];
  const totalFDMap: Record<string, number> = {};

  // Parse stakeholder rows (row 6+, index 5+)
  for (let i = 5; i < rows.length; i++) {
    const row = rows[i] ?? [];
    const id = toStr(row[0]);
    const name = toStr(row[1]);

    if (!name) continue;
    // Skip section headers / total rows
    if (/^total/i.test(name) || id === "") continue;

    const holdings: Record<string, number> = {};
    let total = 0;

    for (const [colIdxStr, code] of Object.entries(colToClass)) {
      const colIdx = parseInt(colIdxStr, 10);
      const shares = toNum(row[colIdx]);
      if (shares > 0) {
        holdings[code] = (holdings[code] ?? 0) + shares;
        total += shares;
      }
    }

    if (total === 0 && Object.keys(holdings).length === 0) continue;

    stakeholders.push({
      id: id || `stakeholder-${i}`,
      name,
      holdings,
      totalFullyDiluted: total,
      ownershipPercent: 0, // calculated after
    });
    totalFDMap[name] = total;
  }

  // Calculate ownership percentages
  const grandTotal = stakeholders.reduce((s, sh) => s + sh.totalFullyDiluted, 0);
  if (grandTotal > 0) {
    for (const sh of stakeholders) {
      sh.ownershipPercent = sh.totalFullyDiluted / grandTotal;
    }
  }

  // Sort by total fully diluted descending
  stakeholders.sort((a, b) => b.totalFullyDiluted - a.totalFullyDiluted);

  return stakeholders;
}

// ─── Main entry point ─────────────────────────────────────────────────────────

export async function parseCartaExcel(
  buffer: ArrayBuffer
): Promise<CapTableSummary> {
  let workbook: XLSX.WorkBook;
  try {
    workbook = XLSX.read(new Uint8Array(buffer), { type: "array" });
  } catch {
    throw new Error(
      "Failed to read the Excel file. Make sure it is a valid .xlsx or .xls file."
    );
  }

  if (workbook.SheetNames.length === 0) {
    throw new Error("The workbook contains no sheets.");
  }

  // Find the Summary sheet
  const summarySheetName =
    findSheet(workbook, "Summary Cap Table") ??
    findSheet(workbook, "Summary") ??
    workbook.SheetNames[0];

  const summaryRows = readSheet(workbook, summarySheetName);
  if (summaryRows.length < 5) {
    throw new Error(
      `The sheet "${summarySheetName}" does not appear to be a Carta cap table (too few rows).`
    );
  }

  const summaryData = parseSummarySheet(summaryRows);

  // Find the Intermediate sheet
  const intermediateSheetName =
    findSheet(workbook, "Intermediate Cap Table") ??
    findSheet(workbook, "Intermediate") ??
    (workbook.SheetNames.length > 1 ? workbook.SheetNames[1] : null);

  let stakeholders: CapTableStakeholder[] = [];
  if (intermediateSheetName) {
    const intermediateRows = readSheet(workbook, intermediateSheetName);
    stakeholders = parseIntermediateSheet(
      intermediateRows,
      summaryData.classes
    );
  }

  return {
    companyName: summaryData.companyName,
    asOfDate: summaryData.asOfDate,
    generatedBy: summaryData.generatedBy,
    totalFullyDilutedShares: summaryData.totalFullyDilutedShares,
    totalCashRaised: summaryData.totalCashRaised,
    classes: summaryData.classes,
    stakeholders,
    optionPool: summaryData.optionPool,
    safes: summaryData.safes,
  };
}
