import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from "@react-pdf/renderer";
import { markdownToPdfElements } from "@/lib/research/markdown-to-pdf";
import type {
  ResearchSessionRow,
  ResearchIterationRow,
} from "@/lib/supabase/types";

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 10,
    fontFamily: "Helvetica",
    color: "#1e293b",
  },
  titlePage: {
    padding: 40,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    height: "100%",
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 16,
    maxWidth: 400,
  },
  subtitle: {
    fontSize: 12,
    color: "#64748b",
    textAlign: "center",
    marginBottom: 8,
  },
  brand: {
    fontSize: 10,
    color: "#94a3b8",
    marginTop: 40,
  },
  sectionHeader: {
    fontSize: 14,
    fontWeight: "bold",
    marginTop: 20,
    marginBottom: 8,
    paddingBottom: 4,
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
  },
  promptLabel: {
    fontSize: 9,
    fontWeight: "bold",
    color: "#64748b",
    marginBottom: 4,
  },
  promptText: {
    fontSize: 9,
    color: "#475569",
    backgroundColor: "#f8fafc",
    padding: 8,
    borderRadius: 4,
    marginBottom: 12,
    lineHeight: 1.4,
  },
  iterationDivider: {
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
    marginVertical: 16,
  },
  footer: {
    position: "absolute",
    bottom: 20,
    left: 40,
    right: 40,
    flexDirection: "row",
    justifyContent: "space-between",
    fontSize: 8,
    color: "#94a3b8",
  },
});

interface ResearchPdfDocumentProps {
  session: ResearchSessionRow;
  iterations: ResearchIterationRow[];
}

export function ResearchPdfDocument({
  session,
  iterations,
}: ResearchPdfDocumentProps) {
  const date = new Date(session.created_at).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return (
    <Document>
      {/* Title page */}
      <Page size="A4" style={styles.titlePage}>
        <Text style={styles.title}>{session.title}</Text>
        <Text style={styles.subtitle}>Financial Research Report</Text>
        <Text style={styles.subtitle}>{date}</Text>
        <Text style={styles.subtitle}>
          {iterations.length} iteration{iterations.length !== 1 ? "s" : ""}
        </Text>
        <Text style={styles.brand}>Generated by ShardCFO</Text>
      </Page>

      {/* Iteration pages */}
      {iterations.map((iteration) => (
        <Page key={iteration.id} size="A4" style={styles.page} wrap>
          <Text style={styles.sectionHeader}>
            Iteration {iteration.iteration_num}
          </Text>

          <Text style={styles.promptLabel}>RESEARCH PROMPT</Text>
          <Text style={styles.promptText}>
            {iteration.generated_prompt || iteration.user_prompt}
          </Text>

          {iteration.result_markdown && (
            <View>
              <Text style={styles.promptLabel}>FINDINGS</Text>
              {markdownToPdfElements(iteration.result_markdown)}
            </View>
          )}

          {/* Footer */}
          <View style={styles.footer} fixed>
            <Text>ShardCFO Research</Text>
            <Text
              render={({ pageNumber, totalPages }) =>
                `Page ${pageNumber} of ${totalPages}`
              }
            />
          </View>
        </Page>
      ))}
    </Document>
  );
}
